// Init.compute
#pragma kernel InitOrganicsKernel
#pragma kernel InitEnergyKernel
#pragma kernel InitCells
#pragma kernel CleanCells
#pragma kernel CleanGenomes

#include "Defines.hlsl"
#include "CommonParams.hlsl"

cbuffer InitParams
{
    float _StartOrganic;
    float _MeanEnergy;
    uint _CellRowCount;
};

#include "Common.hlsl"

[numthreads(8,8,1)]
void InitOrganicsKernel(uint3 id : SV_DispatchThreadID)
{
    if (id.x > _Width || id.y > _Height) return;

    uint2 pos = uint2(id.x, id.y);
    float2 cur = _SoilTexRW[pos];
    cur.x = _StartOrganic;
    _SoilTexRW[pos] = cur;
}

[numthreads(8,8,1)]
void InitEnergyKernel(uint3 id : SV_DispatchThreadID)
{
    if (id.x > _Width || id.y > _Height) return;

    uint2 pos = uint2(id.x, id.y);
    float2 cur = _SoilTexRW[pos];
    cur.y = _MeanEnergy;
    _SoilTexRW[pos] = cur;
}

[numthreads(1,1,1)]
void InitCells(uint3 id : SV_DispatchThreadID)
{
    uint2 cellPos = id.xy * 32;
    uint cellIdx = PosToIdx(cellPos);

    Cell newCell = (Cell)0;
    newCell.cellType = CELLTYPE_SPROUT;
    newCell.genomeId = AllocateRandomGenome(cellPos);
    newCell.parentDir = 0xFFFFFFFF;
    newCell.energy = 10.0;

    _CellsRW[cellIdx] = newCell;
}

[numthreads(8,8,1)]
void CleanCells(uint3 id : SV_DispatchThreadID)
{
    uint2 cellPos = id.xy;
    uint cellIdx = PosToIdx(cellPos);
    _CellsRW[cellIdx] = (Cell)0;
}

[numthreads(64,1,1)]
void CleanGenomes(uint3 id : SV_DispatchThreadID)
{
    uint genIdx = id.x;
    if (genIdx >= _Width * _Height) return;
    _Genomes[genIdx] = (Genome)0;
}
