#pragma kernel DiffuseEnergyKernel
#pragma kernel LeafKernel
#pragma kernel RootKernel
#pragma kernel AntennaKernel
#pragma kernel RerouteKernel
#pragma kernel TransportKernel
#pragma kernel AbsorptionKernel
#pragma kernel DeathKernel
#pragma kernel KillKernel
#pragma kernel SeedKernel
#pragma kernel StatsKernel

#include "Defines.hlsl"
#include "CommonParams.hlsl"

RWStructuredBuffer<SimStats> _Stats; // small stats buffer

#include "CommonLib.hlsl"
#include "CellLib.hlsl"
// #include "CellBehavior.hlsl"

[numthreads(8,8,1)]
void DiffuseEnergyKernel(uint3 id : SV_DispatchThreadID)
{
    GUARD_CELL_COORD(id.xy);
    READ_SOIL(id.xy);

    float soilOrg = soil.x;
    float soilNrg = soil.y;

    float nrgAround = 0.0;
    for (int dx = -1; dx <= 1; ++dx) {
        for (int dy = -1; dy <= 1; ++dy) {
            uint2 coord = MoveCoord(cellPos, int2(dx,dy));
            float2 coordSoil = _SoilTexRO[coord];
            nrgAround += coordSoil.y;
        }
    }

    float nextNrg = soilNrg;
    // 1. make diffusion with sunlight
    // nextNrg = lerp(soilNrg, _Sunlight * 0.5, _DiffusionRate * _Timestep);
    // 2. make diffusion with neighbors
    nextNrg = lerp(soilNrg, nrgAround / 9.0, _DiffusionRate * _Timestep);

    _SoilTexWO[cellPos] = float2(soilOrg, nextNrg);
}

[numthreads(8,8,1)]
void LeafKernel(uint3 id : SV_DispatchThreadID)
{
    GUARD_CELL_COORD(id.xy);
    READ_CELL(id.xy);
    if (cell.cellType != CELLTYPE_LEAF) return; // only leaves

    float organicsLocal = 0.0;
    float organicsNeighbors = 0.0;
    uint freeSpace = 0;
    uint2 mapSize = uint2(_Width,_Height);
    for (int dx = -1; dx <= 1; ++dx) {
        for (int dy = -1; dy <= 1; ++dy) {
            uint2 coord = (cellPos + uint2(dx,dy) + mapSize) % mapSize;
            float2 soil = _SoilTexRO[coord];
            organicsLocal += soil.x * (dx == 0 && dy == 0);
            organicsNeighbors += soil.x * (1 - (dx == 0 && dy == 0));
            uint coordIdx = PosToIdx(coord);
            freeSpace += _CellsRO[coordIdx].cellType == 0;
        }
    }
    float organicsAround = organicsLocal + (organicsNeighbors * 0.125);
    // float produced = organicsAround * _Sunlight * _Timestep;
    float produced = organicsAround * ((float)freeSpace / 7.0) * _Sunlight * _Timestep;
    cell.energy += produced * _Timestep;
    _CellsRO[cellIdx] = cell;
}

[numthreads(8,8,1)]
void RootKernel(uint3 id : SV_DispatchThreadID)
{
    GUARD_CELL_COORD(id.xy);
    READ_CELL(id.xy);
    uint cellType = cell.cellType;
    float2 cellSoil = _SoilTexRO[cellPos];
    // if (cellType != CELLTYPE_ROOT) return; // only roots

    float cellCollectNrg = 0.0;
    float soilDepleteOrg = 0.0;
    float localOrganics = 0.0;
    // look at organics around -> add energy to the root in this cell
    // look at roots around -> deplete organics from this cell
    uint2 mapSize = uint2(_Width,_Height);
    for (int dx = -1; dx <= 1; ++dx) {
        for (int dy = -1; dy <= 1; ++dy) {
            uint2 neighborPos = (cellPos + uint2(dx,dy) + mapSize) % mapSize;
            float2 neighborSoil = _SoilTexRO[neighborPos];

            uint neighborIdx = PosToIdx(neighborPos);
            Cell neighborCell = _CellsRO[neighborIdx];

            float neighborOrganics = neighborSoil.x * (dx == 0 && dy == 0 ? 1.0 : 0.125);
            localOrganics += neighborSoil.x * (dx == 0 && dy == 0);
            float cellNrgDelta = min(neighborOrganics, _OrgAbsorbSpeed * _Timestep);
            cellCollectNrg += cellNrgDelta;
            localOrganics -= cellNrgDelta * (dx == 0 && dy == 0);

            float neighborRoots = (neighborCell.cellType == CELLTYPE_ROOT) * (dx == 0 && dy == 0 ? 1.0 : 0.125);
            float soilOrgDelta = min(cellSoil.y, neighborRoots * _OrgAbsorbSpeed * _Timestep);
            soilDepleteOrg += soilOrgDelta;
        }
    }

    _SoilTexWO[cellPos] = float2(cellSoil.x - soilDepleteOrg, cellSoil.y); // deplete organics

    if (cellType == CELLTYPE_ROOT && localOrganics <= 0) ConvertToWood(cell);
    cell.energy += cellCollectNrg * (cellType == CELLTYPE_ROOT);
    _CellsRO[cellIdx] = cell;
}

[numthreads(8,8,1)]
void AntennaKernel(uint3 id : SV_DispatchThreadID)
{
    GUARD_CELL_COORD(id.xy);
    READ_CELL(id.xy);
    uint cellType = cell.cellType;
    float2 cellSoil = _SoilTexRO[cellPos];
    // if (cellType != CELLTYPE_ANTENNA) return; // only antennas

    float cellCollectNrg = 0.0;
    float soilDepleteNrg = 0.0;
    float localEnergy = 0.0;
    // look at energy around -> add energy to the antenna in this cell
    // look at roots around -> deplete energy from this cell
    uint2 mapSize = uint2(_Width,_Height);
    for (int dx = -1; dx <= 1; ++dx) {
        for (int dy = -1; dy <= 1; ++dy) {
            uint2 neighborPos = (cellPos + uint2(dx,dy) + mapSize) % mapSize;
            float2 neighborSoil = _SoilTexRO[neighborPos];

            uint neighborIdx = PosToIdx(neighborPos);
            Cell neighborCell = _CellsRO[neighborIdx];

            float neighborNrg = neighborSoil.y * (dx == 0 && dy == 0 ? 1.0 : 0.125);
            localEnergy += neighborSoil.y * (dx == 0 && dy == 0);
            float cellNrgDelta = min(neighborNrg, _NrgAbsorbSpeed * _Timestep);
            cellCollectNrg += cellNrgDelta;
            localEnergy -= cellNrgDelta * (dx == 0 && dy == 0);

            float neighborAntennas = (neighborCell.cellType == CELLTYPE_ANTENNA) * (dx == 0 && dy == 0 ? 1.0 : 0.125);
            float soilNrgDelta = min(cellSoil.y, neighborAntennas * _NrgAbsorbSpeed * _Timestep);
            soilDepleteNrg += soilNrgDelta;
        }
    }

    _SoilTexWO[cellPos] = float2(cellSoil.x, cellSoil.y - soilDepleteNrg); // deplete energy

    if (cellType == CELLTYPE_ANTENNA && localEnergy <= 0) ConvertToWood(cell);
    cell.energy += cellCollectNrg * (cellType == CELLTYPE_ANTENNA);
    _CellsRO[cellIdx] = cell;
}

[numthreads(8,8,1)]
void RerouteKernel(uint3 id : SV_DispatchThreadID)
{
    GUARD_CELL_COORD(id.xy);
    READ_CELL(id.xy);

    uint cellType = cell.cellType;
    if (cellType == 0 || cellType > CELLTYPE_SEED) { // only valid cells transfer energy
        _CellsWO[cellIdx] = cell;
        return;
    }

    for (uint dir = 0; dir < 4; ++dir) {
        READ_NEIGHBOR_CELL(cellPos, dir);

        bool isNeighborValid = neighborCell.cellType > 0;
        int toNeighbor = dir;
        int fromNeighbor = RotateDir(toNeighbor, DIR_B);

        bool canSend = isNeighborValid && HasOutFlow(cell, toNeighbor);
        // if two cells wants to send energy to each other then wins the one that sending energy to its parent
        // another one should stop sending energy here and potentially change flow direction.
        bool isNeighborSending = isNeighborValid && HasOutFlow(neighborCell, fromNeighbor);
        canSend = canSend && (!isNeighborSending || cell.parentDir == toNeighbor);
        SetOutFlow(cell, toNeighbor, canSend);
        SetInFlow(cell, toNeighbor, isNeighborSending);
    }

    if (cell.cellType == CELLTYPE_WOOD && GetOutFlow(cell) == 0 && IsCellHasParent(cell))
        SetOutFlow(cell, cell.parentDir, 1);

    _CellsWO[cellIdx] = cell;
}

[numthreads(8,8,1)]
void TransportKernel(uint3 id : SV_DispatchThreadID)
{
    GUARD_CELL_COORD(id.xy);
    READ_CELL(id.xy);

    uint cellType = cell.cellType;
    if (cellType == 0 || cellType > CELLTYPE_SEED) { // only valid cells transfer energy
        _CellsWO[cellIdx] = cell;
        return;
    }

    uint neighborsToSend = DirectionsToSendEnergy(cell);
    float amountToSend = min(cell.energy * _NrgTransportSpeed * _Timestep * neighborsToSend, cell.energy);
    float toSend = step(_NrgTransportMin, cell.energy) * amountToSend;

    float toReceive = 0.0;
    // Pull-based transport: each cell attempts to pull energy from neighbors
    // or deplete self energy for the cells in directions of energy flow
    for (uint dir = 0; dir < 4; ++dir) {
        READ_NEIGHBOR_CELL(cellPos, dir);

        int toNeighbor = dir;
        uint neighborNeighborsToSend = DirectionsToSendEnergy(neighborCell);

        // Check if the neighbor is willing to send energy toward this cell.
        uint canReceive = HasInFlow(cell, toNeighbor);
        float amountToReceive = min(neighborCell.energy * _NrgTransportSpeed * _Timestep, neighborCell.energy / (float)neighborNeighborsToSend);
        toReceive += canReceive * step(_NrgTransportMin, neighborCell.energy) * amountToReceive;
    }

    cell.energy = max(cell.energy + toReceive - toSend, 0);

    _CellsWO[cellIdx] = cell;
}

[numthreads(8,8,1)]
void AbsorptionKernel(uint3 id : SV_DispatchThreadID)
{
    GUARD_CELL_COORD(id.xy);
    READ_CELL(id.xy);

    if (cell.cellType == 0) return;

    float cost = (cell.cellType == CELLTYPE_SEED ? _LifeNrgSpendSeed : _LifeNrgSpend) * _Timestep;
    cell.energy -= cost;
    _CellsRO[cellIdx] = cell;
}

[numthreads(8,8,1)]
void DeathKernel(uint3 id : SV_DispatchThreadID)
{
    GUARD_CELL_COORD(id.xy);
    READ_CELL(id.xy);

    if (cell.cellType == 0) return;

    uint cellType = cell.cellType;
    float2 soil = _SoilTexRO[cellPos];
    _KillCells[cellIdx] = cellType > 0
        && (cell.energy <= 0.0
            || (cellType != CELLTYPE_ROOT && soil.x > _CriticalOrg)
            || (cellType != CELLTYPE_ANTENNA && soil.y > _CriticalNrg)
            || (cellType < CELLTYPE_SPROUT && !IsCellHasParent(cell) && !IsCellSendEnergy(cell))
            // || (cellType == CELLTYPE_WOOD && c.flowDirs = 0)
        );
}
[numthreads(8,8,1)]
void KillKernel(uint3 id : SV_DispatchThreadID)
{
    GUARD_CELL_COORD(id.xy);
    READ_CELL_SOIL(id.xy);

    // spit organics to soil
    // spit energy from the cell to soil
    for (int dx = -1; dx <= 1; ++dx) {
        for (int dy = -1; dy <= 1; ++dy) {
            uint2 coord = MoveCoord(cellPos, int2(dx,dy));
            uint coordIdx = PosToIdx(coord);
            Cell coordCell = _CellsRO[coordIdx];
            bool killCoordCell = (coordCell.cellType > 0) && _KillCells[coordIdx];
            soil.x += killCoordCell * _CellOrgCost * ((dx == 0 && dy == 0) ? 0.3 : (0.7/8.0));
            soil.y += killCoordCell * coordCell.energy * (dx == 0 && dy == 0);
        }
    }

    bool killCell = _KillCells[cellIdx];

    if (cell.cellType > 0) {
        if (killCell) {
            RemoveCell(cell);
            cell = (Cell)0;
        } else {
            // get rid of neighbors parent refs and energy flow
            for (int dir = 0; dir < 4; ++dir) {
                int toNeighbor = dir;
                uint2 neighborPos = ShiftCoord(cellPos, toNeighbor);
                uint neighborIdx = PosToIdx(neighborPos);
                Cell neighborCell = _CellsRO[neighborIdx];

                if (!_KillCells[neighborIdx] && neighborCell.cellType > 0) continue;

                // remove parent ref on neighbor
                cell.parentDir = cell.parentDir == toNeighbor ? 0xFFFFFFFFu : cell.parentDir;

                // close energy flow to neighbor
                SetOutFlow(cell, toNeighbor, false);
                SetInFlow(cell, toNeighbor, false);
            }
        }
    }

    // clear processed kill flag so subsequent passes don't see it
    _KillCells[cellIdx] = 0;
    _CellsWO[cellIdx] = cell;
    _SoilTexWO[cellPos] = soil;
}

[numthreads(8,8,1)]
void SeedKernel(uint3 id : SV_DispatchThreadID)
{
    GUARD_CELL_COORD(id.xy);
    READ_CELL(id.xy);

    if (cell.cellType != CELLTYPE_SEED) { // only seeds
        return;
    }

    uint seedTimer = UnpackInt1(cell.seedProps);

    // move if single
    [branch]
    if (seedTimer == 255u) {
        ConvertToSprout(cell);
    } else {
        // deplete timer
        --seedTimer;
        SetIntByte(cell.seedProps, seedTimer, 0);

        bool isSingle = IsCellSingle(cellPos, cell);
        uint seedSpeed = UnpackInt3(cell.seedProps);

        [branch]
        if (isSingle && seedSpeed > 0) {
            // Move seed
            uint moveDir = cell.direction;
            uint2 targetCoord = ShiftCoord(cellPos, moveDir);
            uint targetIdx = PosToIdx(targetCoord);

            [branch]
            if (_CellsRO[targetIdx].cellType > 0) {
                // kill target cell and self
                KillCell(targetCoord);
                KillCell(cellPos);
            } else {
                // move using move command
                CommandEntry ce = (CommandEntry)0;
                ce.commandId = CMD_MOVE;
                _CommandBuffer[cellIdx] = ce;
            }
        }
    }
    _CellsRO[cellIdx] = cell;
}

#define THREADS_COUNT 512
groupshared SimStats localBuffer[THREADS_COUNT]; // Займет 20 КБ

[numthreads(THREADS_COUNT,1,1)]
void StatsKernel(uint3 threadId : SV_DispatchThreadID, uint threadGroupIdx : SV_GroupIndex, uint3 groupID : SV_GroupID)
{
    SimStats accumulator = (SimStats)0;

    // Шаг 1: Сбор данных из глобальной памяти
    for (uint i = threadGroupIdx; i < _CellsRO.Length; i += THREADS_COUNT)
    {
        Cell cell = _CellsRO[i];
        float2 soil = _SoilTexRO[IdxToPos(i)];

        uint cellType = cell.cellType;

        accumulator.cellsCount += cellType != 0 ? 1 : 0;
        accumulator.leafsCount += cellType == CELLTYPE_LEAF ? 1 : 0;
        accumulator.rootsCount += cellType == CELLTYPE_ROOT ? 1 : 0;
        accumulator.antennasCount += cellType == CELLTYPE_ANTENNA ? 1 : 0;
        accumulator.woodCount += cellType == CELLTYPE_WOOD ? 1 : 0;
        accumulator.sproutsCount += cellType == CELLTYPE_SPROUT ? 1 : 0;
        accumulator.seedsCount += cellType == CELLTYPE_SEED ? 1 : 0;

        accumulator.cellEnergy += cell.energy;
        accumulator.soilOrganics += soil.x;
        accumulator.soilEnergy += soil.y;
    }

    localBuffer[threadGroupIdx] = accumulator;

    GroupMemoryBarrierWithGroupSync();

    // Шаг 2: Древовидное сложение структуры
    for (uint stride = THREADS_COUNT / 2; stride > 0; stride /= 2)
    {
        if (threadGroupIdx < stride)
        {
            // Покомпонентно складываем поля структуры
            localBuffer[threadGroupIdx].cellsCount += localBuffer[threadGroupIdx + stride].cellsCount;
            localBuffer[threadGroupIdx].leafsCount += localBuffer[threadGroupIdx + stride].leafsCount;
            localBuffer[threadGroupIdx].rootsCount += localBuffer[threadGroupIdx + stride].rootsCount;
            localBuffer[threadGroupIdx].antennasCount += localBuffer[threadGroupIdx + stride].antennasCount;
            localBuffer[threadGroupIdx].woodCount += localBuffer[threadGroupIdx + stride].woodCount;
            localBuffer[threadGroupIdx].sproutsCount += localBuffer[threadGroupIdx + stride].sproutsCount;
            localBuffer[threadGroupIdx].seedsCount += localBuffer[threadGroupIdx + stride].seedsCount;
            localBuffer[threadGroupIdx].cellEnergy += localBuffer[threadGroupIdx + stride].cellEnergy;
            localBuffer[threadGroupIdx].soilOrganics += localBuffer[threadGroupIdx + stride].soilOrganics;
            localBuffer[threadGroupIdx].soilEnergy += localBuffer[threadGroupIdx + stride].soilEnergy;
        }
        GroupMemoryBarrierWithGroupSync();
    }

    // Шаг 3: Запись итоговой структуры
    if (threadGroupIdx == 0)
    {
        _Stats[0] = localBuffer[0];
    }
}
